[features]
seeds = false
skip-lint = false
[programs.localnet]
myepicproject = "2ZmQikrkcD7m9k4zVpGUvjdj5eWvZoXfjaz3EhqTVo64"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nvg/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
